version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-broswers
    steps:
      - checkout
      
      - run:
          name: Jaime
          command: echo Hola Visent.
          
